export const DETECT_NAVBAR = 'DETECT_NAVBAR';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_CARD = 'UPDATE_CARD';
export const CALCULATE_TOTALS = 'CALCULATE_TOTALS';
